// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zctasyibfzehijfoyfsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjdGFzeWliZnplaGlqZm95ZnNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzMTg1NjIsImV4cCI6MjA1MTg5NDU2Mn0.xO1RBdPw05WhtXTHiD91Nm5Vd1dMc84j93I_ztL1_GA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);